#-------------------------------
# General Site Settings

name: MrDemonWolf
google-analytics: UA-xxxx-1

#-------------------------------
# SEO Section

seo:
  twitter-creator: 'https://www.twitter.com/mrdemonwolf'
  twitter-site: 'https://www.twitter.com/mrdemonwolf'
  type: 'website'

#-------------------------------
# Menu Section

menu:
- {title: Home, url: '#'}

#-------------------------------
# Social Icons and URls

social:
- {icon: 'fa-spotify', color: 'spotify-color', url: 'https://example.com'}

#-------------------------------
# Modified Date

modified-date: September 25, 2017

#-------------------------------
